export const LightTheme = {
  palette: {
    headerBackground: "#00cccc",
    panelBackground: "#00cccc",
    loginContainerBackground: "#00cccc",
    registrationContainerBackground: "#00cccc",
    loginPageBackground: "#EFB071",
    registrationPageBackground: "#EFB071",
    authTextColor: "black",
    headerTextColor: "black",
    mainPageBackground: "#EFB071",
    modalBackground: "#202020",
    modalTextColor: "white",
    productCardBackground: "#E0E0E0",
    filterTextColor: "black",
    mobileMenuButton: "#E0E0E0",
    mobileMenuTitle: "#00cccc",
    mobileContentBackground: "#00cccc",
    cartTextColor: "black",
    cartBackground: "#00cccc",
  },
  globals: {
    breakpoints: {
      xs: "361px",
      sm: "576px",
      md: "778px",
      cd: "1000px",
      lg: "1920px",
    },
  },
};
